var data = [{
    "name": "常用",
    "links": [{
        "title": "GitHub",
        "url": "http://github.com/"
    }, {
        "title": "Twitter",
        "url": "http://twitter.com"
    }, {
        "title": "YouTube ",
        "url": "http://www.youtube.com"
    }, {
        "title": "新浪微博",
        "url": "https://weibo.com"
    }, {
        "title": "Freebuf",
        "url": "http://www.freebuf.com/"
    }, {
        "title": "知乎",
        "url": "http://zhihu.com"
    }, {
        "title": "有道云笔记",
        "url": "http://note.youdao.com/"
    }, {
        "title": "网易云音乐",
        "url": "http://music.163.com"
    }, {
        "title": "OSChina",
        "url": "https://www.oschina.net/"
    }, {
        "title": "Bing",
        "url": "http://www.bing.com"
    }, {
        "title": "谷歌翻译",
        "url": "http://translate.google.com"
    }, {
        "title": "网易公开课",
        "url": "https://open.163.com/"
    }, {
        "title": "InfoQ",
        "url": "http://www.infoq.com/cn/"
    }, {
        "title": "36Kr",
        "url": "http://36kr.com/"
    }, {
        "title": "V2ex",
        "url": "https://v2ex.com"
    }, {
        "title": "ProtonMail",
        "url": "https://mail.protonmail.com/login"
    }, {
        "title": "新闻",
        "url": "http://www.people.com.cn/"

    }]
},
    {
        "name": "工具",
        "links": [{
            "title": "Pastebin",
            "url": "https://pastebin.com/"
        }, {
            "title": "Gist",
            "url": "https://gist.github.com"
        }, {
            "title": "Glot",
            "url": "https://glot.io/"
        }, {
            "title": "JSBeautifier",
            "url": "http://jsbeautifier.org/"
        },{
             "title": "BeautifyConverter",
             "url":"https://www.beautifyconverter.com/"
        }, {
            "title": "站长工具",
            "url": "http://tool.chinaz.com/"
        }, {
            "title": "Check-host",
            "url": "https://check-host.net/"
        }, {
            "title": "Who.is",
            "url": "https://who.is/"
        },{
            "title": "Bgp",
            "url": "http://bgp.he.net/"
        }, {
            "title": "Sockslist",
            "url": "https://sockslist.net/"
        },{
            "title": "Dnsdumpster",
            "url": "https://dnsdumpster.com/"
        },{
            "title": "Virustotal.io",
            "url": "https://www.virustotal.com/en/domain/baidu.com/information/"
        },{
            "title": "Hackertarget",
            "url": "https://hackertarget.com/"
        },{
            "title": "Robtex",
            "url": "https://www.robtex.com/"
        }, {
            "title": "天眼查",
            "url": "https://www.tianyancha.com/"
        }, {
            "title": "Httpbin",
            "url": "http://httpbin.org/ip"
        }, {
            "title": "加密解密",
            "url": "http://tool.oschina.net/encrypt"
        }, {
            "title": "IPlogger",
            "url": "https://iplogger.org"
        }, {
            "title": "17ce",
            "url": "http://17ce.com"
        }, {
            "title": "Shodan",
            "url": "https://www.shodan.io/"
        }, {
            "title": "Zoomeye",
            "url": "https://www.zoomeye.org/"
        }, {
            "title": "Fofa",
            "url": "https://fofa.so/"
        }, {
            "title": "Hurl",
            "url": "https://www.hurl.it/"
        }, {
            "title": "二维码",
            "url": "http://jiema.wwei.cn/"
        }]
    }, {
        "name": "文档",
        "links": [
            {
                "title": "Go",
                "url": "https://godoc.org/"
            }, {
                "title": "Python",
                "url": "https://docs.python.org/3/"
            }, {
                "title": "JQuery",
                "url": "http://api.jquery.com/"
            }, {
                "title": "Vue",
                "url": "https://vuejs.org/v2/api/"
            }, {
                "title": "Javascript",
                "url": "https://developer.mozilla.org/bm/docs/Web/JavaScript"
            }, {
                "title": "JDK",
                "url": "https://docs.oracle.com/javase/8/docs/api/"
            }, {
                "title": "Spring",
                "url": "https://spring.io/docs/reference"
            }, {
                "title": "Mybatis",
                "url": "http://www.mybatis.org/mybatis-3/"
            }, {
                "title": "ElasticSearch",
                "url": "https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html"
            }, {
                "title": "MySQL",
                "url": "https://dev.mysql.com/doc/refman/5.7/en/"
            }, {
                "title": "Kali",
                "url": "https://tools.kali.org/tools-listing"
            },
        ]
    }, {
        "name": "安全",
        "links": [{
            "title": "MottoIN",
            "url": "http://www.mottoin.com/"
        }, {
            "title": "安全客",
            "url": "http://bobao.360.cn/"
        }, {
            "title": "圈子",
            "url": "https://www.secquan.org/Login"
        }, {
            "title": "安全脉搏",
            "url": "https://www.secpulse.com/"
        }, {
            "title": "看雪论坛",
            "url": "http://bbs.pediy.com/"
        }, {
            "title": "吾爱破解",
            "url": "http://www.52pojie.cn/"
        }, {
            "title": "先知社区",
            "url": "https://xianzhi.aliyun.com/forum/?spm=a2c0h.8049718.0.0.qoviZO"
        }, {
            "title": "ThreatHunter",
            "url": "https://threathunter.org/"
        }, {
            "title": "小密圈",
            "url": "https://wx.xiaomiquan.com/dweb/"
        }, {
            "title": "乌云Wiki",
            "url": "http://wiki.secbug.net/"
        }, {
            "title": "Sec-News",
            "url": "http://wiki.ioin.in/"
        }, {
            "title": "SecWiki",
            "url": "https://www.sec-wiki.com"
        }, {
            "title": "补天",
            "url": "https://butian.360.cn"
        }, {
            "title": "漏洞盒子",
            "url": "https://www.vulbox.com/"
        }, {
            "title": "SOBUG",
            "url": "https://www.sobug.com/"
        }, {
            "title": "CVE漏洞库",
            "url": "http://cve.mitre.org/"
        }, {
            "title": "Seebug",
            "url": "https://www.seebug.org/category/"
        },{
            "title": "OWASP",
            "url": "https://www.owasp.org/index.php/Testing_Checklist"
        }, {
            "title": "绿盟漏洞库",
            "url": "http://www.nsfocus.net/index.php?act=sec_bug"
        }, {
            "title": "Exploits-DB",
            "url": "https://www.exploit-db.com/"
        }, {
            "title": "SecLists",
            "url": "http://seclists.org/"
        }, {
            "title": "CTFtools",
            "url": "https://www.ctftools.com/"
        }, {
            "title": "CTFwriteup",
            "url": "https://github.com/ctfs/"
        }, {
            "title": "CTFtime",
            "url": "https://ctftime.org/"
        }, {
            "title": "XCTFtime",
            "url": "http://oj.xctf.org.cn/web/login/?next=/"
        }, {
            "title": "360CTF",
            "url": "http://bobao.360.cn/ctf/"
        }, {
            "title": "PwnHub",
            "url": "https://pwnhub.cn/index/"
        }, {
            "title": "i春秋",
            "url": "http://www.ichunqiu.com/"
        }, {
            "title": "Threatbook",
            "url": "https://x.threatbook.cn/"
        }, {
            "title": "注册网站查询",
            "url": "http://www.zhaohuini.com/"
        }, {
            "title": "数据牛",
            "url": "http://www.shuju666.com/"
        }, {
            "title": "华西社工库",
            "url": "http://cha.hx99.net/"
        }, {
            "title": "FIND密码",
            "url": "https://usa.findmima.com/"
        }, {
            "title": "Cms识别",
            "url": "http://whatweb.bugscaner.com/look/"
        }, {
            "title": "子域名",
            "url": "https://phpinfo.me/domain/"
        }, {
            "title": "备案查询",
            "url": "http://www.beianbeian.com/"
        }, {
            "title": "漏扫测试平台",
            "url": "http://demo.aisec.cn/demo/"
        }, {
            "title": "C段查询",
            "url": "http://www.webscan.cc/"
        }, {
            "title": "旁站查询",
            "url": "https://phpinfo.me/bing.php"
        }, {
            "title": "百度Webshell检测",
            "url": "http://scanner.baidu.com/#/pages/intro"
        }, {
            "title": "xss-scan",
            "url": "http://xss-scanner.com/"
        }, {
            "title": "XSS'OR",
            "url": "http://xssor.io/"
        }, {
            "title": "360Apk检测",
            "url": "http://appscan.360.cn/"
        }, {
            "title": "腾讯Apk检测",
            "url": "http://service.security.tencent.com/kingkong"
        }, {
            "title": "哈勃",
            "url": "https://habo.qq.com/"
        }, {
            "title": "APK逆向",
            "url": "https://android.fallible.co/"
        }, {
            "title": "Apk检测",
            "url": "http://m.qq.com/security_lab/scans_online.jsp"
        }, {
            "title": "极速代理",
            "url": "http://superfastip.com/welcome/getips"
        }, {
            "title": "安恒漏洞检测",
            "url": "http://0day.websaas.com.cn/"
        }, {
            "title": "知道创宇Paper",
            "url": "http://paper.seebug.org/"
        }, {
            "title": "长亭科技博客",
            "url": "https://blog.chaitin.cn/"
        }, {
            "title": "阿尔法实验室",
            "url": "http://blog.topsec.com.cn/"
        }, {
            "title": "奇虎360博客",
            "url": "http://blogs.360.cn/"
        }, {
            "title": "四叶草安全",
            "url": "http://lab.seclover.com/"
        }, {
            "title": "安恒研究院",
            "url": "http://seclab.dbappsecurity.com.cn/"
        }, {
            "title": "Lijiejie",
            "url": "http://www.lijiejie.com/"
        }, {
            "title": "Phithon",
            "url": "https://www.leavesongs.com/"
        }, {
            "title": "PHP & Java",
            "url": "http://javaweb.org/"
        }, {
            "title": "梧桐雨",
            "url": "http://wutongyu.info/"
        },{
            "title": "Rickgray",
            "url": "http://rickgray.me/"
        },{
            "title": "Ricterz",
            "url":"https://ricterz.me/"
        }, {
            "title": "Ricky Hao",
            "url": "https://rickyhao.com/"
        }, {
            "title": "JoyChou",
            "url": "http://www.joychou.org"
        }, {
            "title": "腾讯SRC",
            "url": "https://security.tencent.com/"
        }, {
            "title": "阿里SRC",
            "url": "http://security.taobao.com/"
        }, {
            "title": "百度SRC",
            "url": "http://sec.baidu.com/"
        }, {
            "title": "360SRC",
            "url": "http://security.360.cn/"
        }, {
            "title": "京东SRC",
            "url": "http://security.jd.com/"
        }, {
            "title": "搜狗SRC",
            "url": "http://sec.sogou.com/"
        }, {
            "title": "苏宁SRC",
            "url": "https://security.suning.com/"
        }, {
            "title": "网易SRC",
            "url": "http://anquan.163.com/"
        }, {
            "title": "小米SRC",
            "url": "https://sec.xiaomi.com/"
        }, {
            "title": "滴滴SRC",
            "url": "http://sec.didichuxing.com/"
        }, {
            "title": "陌陌SRC",
            "url": "https://security.immomo.com/"
        }, {
            "title": "斗鱼SRC",
            "url": "https://security.douyu.com/"
        }, {
            "title": "爱奇艺SRC",
            "url": "https://security.iqiyi.com/"
        }, {
            "title": "饿了吗SRC",
            "url": "https://security.ele.me/"
        }, {
            "title": "哔哩哔哩SRC",
            "url": "http://security.bilibili.com/"
        }, {
            "title": "欢聚时代SRC",
            "url": "http://security.yy.com/"
        }, {
            "title": "深信服SRC",
            "url": "http://security.sangfor.com.cn/"
        }, {
            "title": "唯品会SRC",
            "url": "https://sec.vip.com/"
        }, {
            "title": "去哪儿SRC",
            "url": "http://security.qunar.com/"
        }, {
            "title": "顺丰SRC",
            "url": "http://sfsrc.sf-express.com/rank"
        }, {
            "title": "迅雷SRC",
            "url": "http://safe.xunlei.com/"
        }, {
            "title": "微博SRC",
            "url": "http://wsrc.weibo.com/"
        }, {
            "title": "途牛SRC",
            "url": "http://sec.tuniu.com/"
        }]
    },
    {
        "name": "财经",
        "links": [{
            "title": "雪球",
            "url": "http://xueqiu.com"
        }, {
            "title": "BTChina",
            "url": "https://www.btcchina.com/"
        }, {
            "title": "财联社",
            "url": "http://cailianpress.com/"
        }, {
            "title": "新闻联播",
            "url": "http://mrxwlb.com/"
        }, {
            "title": "Vsat资讯",
            "url": "http://webclient.vsatauth.com/ycpj/CacheHTML/VsatZC/VsatZC.html"
        }, {
            "title": "实时行情",
            "url": "https://wallstreetcn.com/markets"
        }, {
            "title": "券商研报",
            "url": "http://www.nxny.com/"
        }, {
            "title": "业绩报表",
            "url": "http://data.eastmoney.com/bbsj/"
        }]
    },
    {
        "name": "其他",
        "links": [{
            "title": "天天美剧",
            "url": "http://www.ttmeiju.com"
        }, {
            "title": "水木社区",
            "url": "http://www.newsmth.net"
        }, {
            "title": "Solidot",
            "url": "http://www.solidot.org/"
        }, {
            "title": "电影天堂",
            "url": "http://www.dy2018.com"
        }, {
            "title": "豆瓣电影",
            "url": "https://movie.douban.com/"
        }]
    },
    {
        "name": "设计",
        "links": [{
            "title": "Unsplash",
            "url": "http://unsplash.com"
        }, {
            "title": "Easyicon",
            "url": "http://www.easyicon.net/"
        }, {
            "title": "Iconfont",
            "url": "http://www.iconfont.cn/"
        }, {
            "title": "Dribbble",
            "url": "https://dribbble.com/"
        }, {
            "title": "花瓣",
            "url": "http://huaban.com/"
        }, {
            "title": "Behance",
            "url": "https://www.behance.net/"
        }, {
            "title": "优设导航",
            "url": "http://hao.uisdc.com/"
        }, {
            "title": "Lava360",
            "url": "http://lava360.com"
        }, {
            "title": "UI中国",
            "url": "http://www.ui.cn/"
        }, {
            "title": "设计癖",
            "url": "http://www.shejipi.com/"
        }]
    }, {
        "name": "常用下载",
        "links": [{
            "title": "chrome",
            "url": "https://www.google.com/chrome/browser/desktop/?standalone=1"
        }, {
            "title": "VSCode",
            "url": "https://code.visualstudio.com/"
        }, {
            "title": "Idea",
            "url": "https://www.jetbrains.com/idea/download/#section=windows"
        }, {
            "title": "JDK",
            "url": "http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html"
        }, {
            "title": "7z",
            "url": "http://www.7-zip.org/download.html"
        }, {
            "title": "Putty",
            "url": "https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html"
        }, {
            "title": "Shadowsocks",
            "url": "https://github.com/shadowsocks/shadowsocks-windows/releases"
        }, {
            "title": "Prntscr",
            "url": "https://app.prntscr.com/en/download.html"
        }, {
            "title": "Go",
            "url": "https://golang.org/dl/"
        }, {
            "title": "Python",
            "url": "https://www.python.org/downloads/"
        }, {
            "title": "Burp",
            "url": "https://portswigger.net/burp/freedownload"
        }, {
            "title": "Nmap",
            "url": "https://nmap.org/dist/nmap-7.60-setup.exe"
        }, {
            "title": "NodeJS",
            "url": "https://nodejs.org/en/download/"
        }, {
            "title": "WinPcap",
            "url": "https://www.winpcap.org/install/"
        }, {
            "title": "Wireshark",
            "url": "https://www.wireshark.org/download.html"
        }, {
            "title": "Git",
            "url": "https://git-scm.com/download/win"
        }, {
            "title": "JD-GUI",
            "url": "http://jd.benow.ca/"
        }, {
            "title": "Bind",
            "url": "https://www.isc.org/downloads/bind/"
        }, {
            "title": "Everything",
            "url": "http://www.voidtools.com/downloads/"
        }, {
            "title": "VirtualBox",
            "url": "https://www.virtualbox.org/wiki/Downloads"
        }, {
            "title": "Eclipse",
            "url": "http://www.eclipse.org/downloads/eclipse-packages/"
        }, {
            "title": "FDM",
            "url": "https://dn3.freedownloadmanager.org/5/5.1-latest/fdm5_x64_setup.exe"
        }, {
            "title": "Notepad++",
            "url": "https://notepad-plus-plus.org/download/v7.5.1.html"
        }]
    }
];
